prompt PL/SQL Developer Export Tables for user SYS@//77.222.37.9:1521/FREEPDB1
prompt Created by alex on воскресенье, 23 март 2025 г.
set feedback off
set define off

prompt Disabling triggers for ELD_EDUCATIONAL_INSTITUTIONS_TYPES...
alter table ELD_EDUCATIONAL_INSTITUTIONS_TYPES disable all triggers;
prompt Disabling triggers for ELD_REGIONS...
alter table ELD_REGIONS disable all triggers;
prompt Disabling triggers for ELD_SETTLEMENTS...
alter table ELD_SETTLEMENTS disable all triggers;
prompt Disabling triggers for ELD_EDUCATIONAL_INSTITUTIONS...
alter table ELD_EDUCATIONAL_INSTITUTIONS disable all triggers;
prompt Disabling triggers for ELD_ADMINISTRATORS...
alter table ELD_ADMINISTRATORS disable all triggers;
prompt Disabling triggers for ELD_TEACHERS...
alter table ELD_TEACHERS disable all triggers;
prompt Disabling triggers for ELD_CLASSES...
alter table ELD_CLASSES disable all triggers;
prompt Disabling triggers for ELD_SCHOOL_SUBJECTS...
alter table ELD_SCHOOL_SUBJECTS disable all triggers;
prompt Disabling triggers for ELD_TEACHER_ASSIGNMENTS...
alter table ELD_TEACHER_ASSIGNMENTS disable all triggers;
prompt Disabling triggers for ELD_GROUPS...
alter table ELD_GROUPS disable all triggers;
prompt Disabling triggers for ELD_GRADEBOOK_DAYS...
alter table ELD_GRADEBOOK_DAYS disable all triggers;
prompt Disabling triggers for ELD_SCHOOL_STUDENTS...
alter table ELD_SCHOOL_STUDENTS disable all triggers;
prompt Disabling triggers for ELD_GRADEBOOK_ATTENDANCES...
alter table ELD_GRADEBOOK_ATTENDANCES disable all triggers;
prompt Disabling triggers for ELD_GRADEBOOK_SCORES...
alter table ELD_GRADEBOOK_SCORES disable all triggers;
prompt Disabling triggers for ELD_GROUP_MEMBERS...
alter table ELD_GROUP_MEMBERS disable all triggers;
prompt Disabling triggers for ELD_IMAGES...
alter table ELD_IMAGES disable all triggers;
prompt Disabling triggers for ELD_MESSAGES...
alter table ELD_MESSAGES disable all triggers;
prompt Disabling triggers for ELD_NEWS...
alter table ELD_NEWS disable all triggers;
prompt Disabling triggers for ELD_NEW_COMMENTS...
alter table ELD_NEW_COMMENTS disable all triggers;
prompt Disabling triggers for ELD_PARENTS...
alter table ELD_PARENTS disable all triggers;
prompt Disabling triggers for ELD_PARENTS_TYPES...
alter table ELD_PARENTS_TYPES disable all triggers;
prompt Disabling triggers for ELD_QUARTER_SCORES...
alter table ELD_QUARTER_SCORES disable all triggers;
prompt Disabling triggers for ELD_SCHEDULE...
alter table ELD_SCHEDULE disable all triggers;
prompt Disabling triggers for ELD_SCHOOL_STUDENTS_AND_PARENTS...
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS disable all triggers;
prompt Disabling triggers for ELD_SHEDULE_LESSONS...
alter table ELD_SHEDULE_LESSONS disable all triggers;
prompt Disabling triggers for ELD_USER_COMMENTS...
alter table ELD_USER_COMMENTS disable all triggers;
prompt Disabling triggers for ELD_USERS_TYPES...
alter table ELD_USERS_TYPES disable all triggers;
prompt Disabling foreign key constraints for ELD_SETTLEMENTS...
alter table ELD_SETTLEMENTS disable constraint S_R_ID;
prompt Disabling foreign key constraints for ELD_EDUCATIONAL_INSTITUTIONS...
alter table ELD_EDUCATIONAL_INSTITUTIONS disable constraint EI_EIT_ID;
alter table ELD_EDUCATIONAL_INSTITUTIONS disable constraint EI_S_ID;
prompt Disabling foreign key constraints for ELD_ADMINISTRATORS...
alter table ELD_ADMINISTRATORS disable constraint A_U_ID;
alter table ELD_ADMINISTRATORS disable constraint U_EI_ID;
prompt Disabling foreign key constraints for ELD_TEACHERS...
alter table ELD_TEACHERS disable constraint T_EI_ID;
alter table ELD_TEACHERS disable constraint T_U_ID;
prompt Disabling foreign key constraints for ELD_CLASSES...
alter table ELD_CLASSES disable constraint C_T_ID;
prompt Disabling foreign key constraints for ELD_TEACHER_ASSIGNMENTS...
alter table ELD_TEACHER_ASSIGNMENTS disable constraint TA_C_ID;
alter table ELD_TEACHER_ASSIGNMENTS disable constraint TA_SS_ID;
alter table ELD_TEACHER_ASSIGNMENTS disable constraint TA_T_ID;
prompt Disabling foreign key constraints for ELD_GROUPS...
alter table ELD_GROUPS disable constraint G_TA_ID;
prompt Disabling foreign key constraints for ELD_GRADEBOOK_DAYS...
alter table ELD_GRADEBOOK_DAYS disable constraint GD_G_ID;
prompt Disabling foreign key constraints for ELD_SCHOOL_STUDENTS...
alter table ELD_SCHOOL_STUDENTS disable constraint SST_C_ID;
alter table ELD_SCHOOL_STUDENTS disable constraint SST_EI_ID;
alter table ELD_SCHOOL_STUDENTS disable constraint SST_U_ID;
prompt Disabling foreign key constraints for ELD_GRADEBOOK_ATTENDANCES...
alter table ELD_GRADEBOOK_ATTENDANCES disable constraint GA_GD_ID;
alter table ELD_GRADEBOOK_ATTENDANCES disable constraint GA_SST_ID;
prompt Disabling foreign key constraints for ELD_GRADEBOOK_SCORES...
alter table ELD_GRADEBOOK_SCORES disable constraint GS_GD_ID;
alter table ELD_GRADEBOOK_SCORES disable constraint GS_SST_ID;
prompt Disabling foreign key constraints for ELD_GROUP_MEMBERS...
alter table ELD_GROUP_MEMBERS disable constraint GM_G_ID;
alter table ELD_GROUP_MEMBERS disable constraint GM_SST_ID;
prompt Disabling foreign key constraints for ELD_IMAGES...
alter table ELD_IMAGES disable constraint I_EI_ID;
prompt Disabling foreign key constraints for ELD_MESSAGES...
alter table ELD_MESSAGES disable constraint M_U_GETTER_ID;
alter table ELD_MESSAGES disable constraint M_U_SENDER_ID;
prompt Disabling foreign key constraints for ELD_NEWS...
alter table ELD_NEWS disable constraint N_U_OWNER_ID;
prompt Disabling foreign key constraints for ELD_NEW_COMMENTS...
alter table ELD_NEW_COMMENTS disable constraint NC_N_GETTER_ID;
alter table ELD_NEW_COMMENTS disable constraint NC_U_GETTER_ID;
prompt Disabling foreign key constraints for ELD_PARENTS...
alter table ELD_PARENTS disable constraint P_EI_ID;
alter table ELD_PARENTS disable constraint P_U_ID;
prompt Disabling foreign key constraints for ELD_QUARTER_SCORES...
alter table ELD_QUARTER_SCORES disable constraint QS_SS_ID;
alter table ELD_QUARTER_SCORES disable constraint QS_SST_ID;
prompt Disabling foreign key constraints for ELD_SCHOOL_STUDENTS_AND_PARENTS...
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS disable constraint SSTAP_P_ID;
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS disable constraint SSTAP_PT_ID;
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS disable constraint SSTAP_SST_ID;
prompt Disabling foreign key constraints for ELD_SHEDULE_LESSONS...
alter table ELD_SHEDULE_LESSONS disable constraint SL_G_ID;
alter table ELD_SHEDULE_LESSONS disable constraint SL_SH_D;
alter table ELD_SHEDULE_LESSONS disable constraint SL_TA_ID;
prompt Disabling foreign key constraints for ELD_USER_COMMENTS...
alter table ELD_USER_COMMENTS disable constraint UC_U_GETTER_ID;
alter table ELD_USER_COMMENTS disable constraint UC_U_SENDER_ID;
prompt Deleting ELD_USERS_TYPES...
delete from ELD_USERS_TYPES;
commit;
prompt Deleting ELD_USER_COMMENTS...
delete from ELD_USER_COMMENTS;
commit;
prompt Deleting ELD_SHEDULE_LESSONS...
delete from ELD_SHEDULE_LESSONS;
commit;
prompt Deleting ELD_SCHOOL_STUDENTS_AND_PARENTS...
delete from ELD_SCHOOL_STUDENTS_AND_PARENTS;
commit;
prompt Deleting ELD_SCHEDULE...
delete from ELD_SCHEDULE;
commit;
prompt Deleting ELD_QUARTER_SCORES...
delete from ELD_QUARTER_SCORES;
commit;
prompt Deleting ELD_PARENTS_TYPES...
delete from ELD_PARENTS_TYPES;
commit;
prompt Deleting ELD_PARENTS...
delete from ELD_PARENTS;
commit;
prompt Deleting ELD_NEW_COMMENTS...
delete from ELD_NEW_COMMENTS;
commit;
prompt Deleting ELD_NEWS...
delete from ELD_NEWS;
commit;
prompt Deleting ELD_MESSAGES...
delete from ELD_MESSAGES;
commit;
prompt Deleting ELD_IMAGES...
delete from ELD_IMAGES;
commit;
prompt Deleting ELD_GROUP_MEMBERS...
delete from ELD_GROUP_MEMBERS;
commit;
prompt Deleting ELD_GRADEBOOK_SCORES...
delete from ELD_GRADEBOOK_SCORES;
commit;
prompt Deleting ELD_GRADEBOOK_ATTENDANCES...
delete from ELD_GRADEBOOK_ATTENDANCES;
commit;
prompt Deleting ELD_SCHOOL_STUDENTS...
delete from ELD_SCHOOL_STUDENTS;
commit;
prompt Deleting ELD_GRADEBOOK_DAYS...
delete from ELD_GRADEBOOK_DAYS;
commit;
prompt Deleting ELD_GROUPS...
delete from ELD_GROUPS;
commit;
prompt Deleting ELD_TEACHER_ASSIGNMENTS...
delete from ELD_TEACHER_ASSIGNMENTS;
commit;
prompt Deleting ELD_SCHOOL_SUBJECTS...
delete from ELD_SCHOOL_SUBJECTS;
commit;
prompt Deleting ELD_CLASSES...
delete from ELD_CLASSES;
commit;
prompt Deleting ELD_TEACHERS...
delete from ELD_TEACHERS;
commit;
prompt Deleting ELD_ADMINISTRATORS...
delete from ELD_ADMINISTRATORS;
commit;
prompt Deleting ELD_EDUCATIONAL_INSTITUTIONS...
delete from ELD_EDUCATIONAL_INSTITUTIONS;
commit;
prompt Deleting ELD_SETTLEMENTS...
delete from ELD_SETTLEMENTS;
commit;
prompt Deleting ELD_REGIONS...
delete from ELD_REGIONS;
commit;
prompt Deleting ELD_EDUCATIONAL_INSTITUTIONS_TYPES...
delete from ELD_EDUCATIONAL_INSTITUTIONS_TYPES;
commit;
prompt Loading ELD_EDUCATIONAL_INSTITUTIONS_TYPES...
insert into ELD_EDUCATIONAL_INSTITUTIONS_TYPES (id, name)
values (1, 'School');
prompt 1 records loaded
prompt Loading ELD_REGIONS...
insert into ELD_REGIONS (id, name)
values (2, 'Минская область');
insert into ELD_REGIONS (id, name)
values (21, 'Гомельская облась');
commit;
prompt 2 records loaded
prompt Loading ELD_SETTLEMENTS...
insert into ELD_SETTLEMENTS (id, name, s_r_id)
values (2, 'г. Солигорск', 2);
insert into ELD_SETTLEMENTS (id, name, s_r_id)
values (3, 'г. Слуцк', 2);
insert into ELD_SETTLEMENTS (id, name, s_r_id)
values (21, 'г. Гомель', 21);
commit;
prompt 3 records loaded
prompt Loading ELD_EDUCATIONAL_INSTITUTIONS...
insert into ELD_EDUCATIONAL_INSTITUTIONS (id, address, email, name, path_image, phone_number, ei_eit_id, ei_s_id)
values (1, 'admin', 'ЛёхаЛох@.com', 'Гуо', null, '+374213', 1, 2);
insert into ELD_EDUCATIONAL_INSTITUTIONS (id, address, email, name, path_image, phone_number, ei_eit_id, ei_s_id)
values (101, 'пр', 'иои', 'вывапр', null, 'папвпа', 1, 2);
commit;
prompt 2 records loaded
prompt Loading ELD_ADMINISTRATORS...
insert into ELD_ADMINISTRATORS (id, email, first_name, last_name, path_image, patronymic, phone_number, a_ei_id, a_u_id)
values (1, 'dsa', 'Лёха', 'Дуб', null, 'Хз', null, 1, 2);
insert into ELD_ADMINISTRATORS (id, email, first_name, last_name, path_image, patronymic, phone_number, a_ei_id, a_u_id)
values (21, '2', '12332', '23', null, '2332', '2', null, 41);
insert into ELD_ADMINISTRATORS (id, email, first_name, last_name, path_image, patronymic, phone_number, a_ei_id, a_u_id)
values (22, '11', '11', '11', null, '11', '11', null, 42);
insert into ELD_ADMINISTRATORS (id, email, first_name, last_name, path_image, patronymic, phone_number, a_ei_id, a_u_id)
values (23, '233', '13', '23', null, '233', '2', 1, 43);
insert into ELD_ADMINISTRATORS (id, email, first_name, last_name, path_image, patronymic, phone_number, a_ei_id, a_u_id)
values (63, '1', '1', '1', null, '1', '1', 1, 143);
insert into ELD_ADMINISTRATORS (id, email, first_name, last_name, path_image, patronymic, phone_number, a_ei_id, a_u_id)
values (64, '2', '1', '22', null, '2', '2', 1, 144);
commit;
prompt 6 records loaded
prompt Loading ELD_TEACHERS...
insert into ELD_TEACHERS (id, email, first_name, last_name, path_image, patronymic, phone_number, t_ei_id, t_u_id)
values (1, null, 'Учила', 'Степанович', null, null, null, 1, 3);
insert into ELD_TEACHERS (id, email, first_name, last_name, path_image, patronymic, phone_number, t_ei_id, t_u_id)
values (2, null, 'уц', 'уцй', null, null, null, 1, 4);
commit;
prompt 2 records loaded
prompt Loading ELD_CLASSES...
insert into ELD_CLASSES (id, name, c_t_id)
values (1, 'class', 1);
prompt 1 records loaded
prompt Loading ELD_SCHOOL_SUBJECTS...
prompt Table is empty
prompt Loading ELD_TEACHER_ASSIGNMENTS...
prompt Table is empty
prompt Loading ELD_GROUPS...
prompt Table is empty
prompt Loading ELD_GRADEBOOK_DAYS...
prompt Table is empty
prompt Loading ELD_SCHOOL_STUDENTS...
insert into ELD_SCHOOL_STUDENTS (id, email, first_name, last_name, path_image, patronymic, phone_number, sst_c_id, sst_ei_id, sst_u_id)
values (1, '@gmail', 'Ник', 'Кор', null, 'Ал', '+375299999', 1, 1, 5);
prompt 1 records loaded
prompt Loading ELD_GRADEBOOK_ATTENDANCES...
prompt Table is empty
prompt Loading ELD_GRADEBOOK_SCORES...
prompt Table is empty
prompt Loading ELD_GROUP_MEMBERS...
prompt Table is empty
prompt Loading ELD_IMAGES...
prompt Table is empty
prompt Loading ELD_MESSAGES...
prompt Table is empty
prompt Loading ELD_NEWS...
prompt Table is empty
prompt Loading ELD_NEW_COMMENTS...
prompt Table is empty
prompt Loading ELD_PARENTS...
insert into ELD_PARENTS (id, email, first_name, last_name, path_image, patronymic, phone_number, u_ei_id, p_u_id, p_ei_id)
values (1, 'вфы', 'Род', 'Кек', null, 'уцй', null, null, 6, 1);
insert into ELD_PARENTS (id, email, first_name, last_name, path_image, patronymic, phone_number, u_ei_id, p_u_id, p_ei_id)
values (21, 'qwe', 'qwe', 'ewq', null, 'sda', 'qwe', null, 81, 1);
insert into ELD_PARENTS (id, email, first_name, last_name, path_image, patronymic, phone_number, u_ei_id, p_u_id, p_ei_id)
values (41, '1', '1', '1', null, '1', '1', null, 121, 1);
commit;
prompt 3 records loaded
prompt Loading ELD_PARENTS_TYPES...
insert into ELD_PARENTS_TYPES (id, name)
values (1, 'Отец');
insert into ELD_PARENTS_TYPES (id, name)
values (2, 'Мать');
insert into ELD_PARENTS_TYPES (id, name)
values (3, 'Бабушка');
insert into ELD_PARENTS_TYPES (id, name)
values (4, 'Дедушка');
insert into ELD_PARENTS_TYPES (id, name)
values (5, 'Опекун');
insert into ELD_PARENTS_TYPES (id, name)
values (6, 'Попечитель');
insert into ELD_PARENTS_TYPES (id, name)
values (7, 'Приемный родитель');
insert into ELD_PARENTS_TYPES (id, name)
values (8, 'Усыновитель');
insert into ELD_PARENTS_TYPES (id, name)
values (9, 'Временный опекун');
commit;
prompt 9 records loaded
prompt Loading ELD_QUARTER_SCORES...
prompt Table is empty
prompt Loading ELD_SCHEDULE...
prompt Table is empty
prompt Loading ELD_SCHOOL_STUDENTS_AND_PARENTS...
insert into ELD_SCHOOL_STUDENTS_AND_PARENTS (id, sstap_p_id, sstap_pt_id, sstap_sst_id)
values (71, 1, 6, 1);
insert into ELD_SCHOOL_STUDENTS_AND_PARENTS (id, sstap_p_id, sstap_pt_id, sstap_sst_id)
values (101, 21, 7, 1);
commit;
prompt 2 records loaded
prompt Loading ELD_SHEDULE_LESSONS...
prompt Table is empty
prompt Loading ELD_USER_COMMENTS...
prompt Table is empty
prompt Loading ELD_USERS_TYPES...
insert into ELD_USERS_TYPES (id, name)
values (1, 'Main admin');
insert into ELD_USERS_TYPES (id, name)
values (2, 'Local admin');
insert into ELD_USERS_TYPES (id, name)
values (3, 'Teacher');
insert into ELD_USERS_TYPES (id, name)
values (4, 'School student');
insert into ELD_USERS_TYPES (id, name)
values (5, 'Parent');
commit;
prompt 5 records loaded
prompt Enabling foreign key constraints for ELD_SETTLEMENTS...
alter table ELD_SETTLEMENTS enable constraint S_R_ID;
prompt Enabling foreign key constraints for ELD_EDUCATIONAL_INSTITUTIONS...
alter table ELD_EDUCATIONAL_INSTITUTIONS enable constraint EI_EIT_ID;
alter table ELD_EDUCATIONAL_INSTITUTIONS enable constraint EI_S_ID;
prompt Enabling foreign key constraints for ELD_ADMINISTRATORS...
alter table ELD_ADMINISTRATORS enable constraint A_U_ID;
alter table ELD_ADMINISTRATORS enable constraint U_EI_ID;
prompt Enabling foreign key constraints for ELD_TEACHERS...
alter table ELD_TEACHERS enable constraint T_EI_ID;
alter table ELD_TEACHERS enable constraint T_U_ID;
prompt Enabling foreign key constraints for ELD_CLASSES...
alter table ELD_CLASSES enable constraint C_T_ID;
prompt Enabling foreign key constraints for ELD_TEACHER_ASSIGNMENTS...
alter table ELD_TEACHER_ASSIGNMENTS enable constraint TA_C_ID;
alter table ELD_TEACHER_ASSIGNMENTS enable constraint TA_SS_ID;
alter table ELD_TEACHER_ASSIGNMENTS enable constraint TA_T_ID;
prompt Enabling foreign key constraints for ELD_GROUPS...
alter table ELD_GROUPS enable constraint G_TA_ID;
prompt Enabling foreign key constraints for ELD_GRADEBOOK_DAYS...
alter table ELD_GRADEBOOK_DAYS enable constraint GD_G_ID;
prompt Enabling foreign key constraints for ELD_SCHOOL_STUDENTS...
alter table ELD_SCHOOL_STUDENTS enable constraint SST_C_ID;
alter table ELD_SCHOOL_STUDENTS enable constraint SST_EI_ID;
alter table ELD_SCHOOL_STUDENTS enable constraint SST_U_ID;
prompt Enabling foreign key constraints for ELD_GRADEBOOK_ATTENDANCES...
alter table ELD_GRADEBOOK_ATTENDANCES enable constraint GA_GD_ID;
alter table ELD_GRADEBOOK_ATTENDANCES enable constraint GA_SST_ID;
prompt Enabling foreign key constraints for ELD_GRADEBOOK_SCORES...
alter table ELD_GRADEBOOK_SCORES enable constraint GS_GD_ID;
alter table ELD_GRADEBOOK_SCORES enable constraint GS_SST_ID;
prompt Enabling foreign key constraints for ELD_GROUP_MEMBERS...
alter table ELD_GROUP_MEMBERS enable constraint GM_G_ID;
alter table ELD_GROUP_MEMBERS enable constraint GM_SST_ID;
prompt Enabling foreign key constraints for ELD_IMAGES...
alter table ELD_IMAGES enable constraint I_EI_ID;
prompt Enabling foreign key constraints for ELD_MESSAGES...
alter table ELD_MESSAGES enable constraint M_U_GETTER_ID;
alter table ELD_MESSAGES enable constraint M_U_SENDER_ID;
prompt Enabling foreign key constraints for ELD_NEWS...
alter table ELD_NEWS enable constraint N_U_OWNER_ID;
prompt Enabling foreign key constraints for ELD_NEW_COMMENTS...
alter table ELD_NEW_COMMENTS enable constraint NC_N_GETTER_ID;
alter table ELD_NEW_COMMENTS enable constraint NC_U_GETTER_ID;
prompt Enabling foreign key constraints for ELD_PARENTS...
alter table ELD_PARENTS enable constraint P_EI_ID;
alter table ELD_PARENTS enable constraint P_U_ID;
prompt Enabling foreign key constraints for ELD_QUARTER_SCORES...
alter table ELD_QUARTER_SCORES enable constraint QS_SS_ID;
alter table ELD_QUARTER_SCORES enable constraint QS_SST_ID;
prompt Enabling foreign key constraints for ELD_SCHOOL_STUDENTS_AND_PARENTS...
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS enable constraint SSTAP_P_ID;
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS enable constraint SSTAP_PT_ID;
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS enable constraint SSTAP_SST_ID;
prompt Enabling foreign key constraints for ELD_SHEDULE_LESSONS...
alter table ELD_SHEDULE_LESSONS enable constraint SL_G_ID;
alter table ELD_SHEDULE_LESSONS enable constraint SL_SH_D;
alter table ELD_SHEDULE_LESSONS enable constraint SL_TA_ID;
prompt Enabling foreign key constraints for ELD_USER_COMMENTS...
alter table ELD_USER_COMMENTS enable constraint UC_U_GETTER_ID;
alter table ELD_USER_COMMENTS enable constraint UC_U_SENDER_ID;
prompt Enabling triggers for ELD_EDUCATIONAL_INSTITUTIONS_TYPES...
alter table ELD_EDUCATIONAL_INSTITUTIONS_TYPES enable all triggers;
prompt Enabling triggers for ELD_REGIONS...
alter table ELD_REGIONS enable all triggers;
prompt Enabling triggers for ELD_SETTLEMENTS...
alter table ELD_SETTLEMENTS enable all triggers;
prompt Enabling triggers for ELD_EDUCATIONAL_INSTITUTIONS...
alter table ELD_EDUCATIONAL_INSTITUTIONS enable all triggers;
prompt Enabling triggers for ELD_ADMINISTRATORS...
alter table ELD_ADMINISTRATORS enable all triggers;
prompt Enabling triggers for ELD_TEACHERS...
alter table ELD_TEACHERS enable all triggers;
prompt Enabling triggers for ELD_CLASSES...
alter table ELD_CLASSES enable all triggers;
prompt Enabling triggers for ELD_SCHOOL_SUBJECTS...
alter table ELD_SCHOOL_SUBJECTS enable all triggers;
prompt Enabling triggers for ELD_TEACHER_ASSIGNMENTS...
alter table ELD_TEACHER_ASSIGNMENTS enable all triggers;
prompt Enabling triggers for ELD_GROUPS...
alter table ELD_GROUPS enable all triggers;
prompt Enabling triggers for ELD_GRADEBOOK_DAYS...
alter table ELD_GRADEBOOK_DAYS enable all triggers;
prompt Enabling triggers for ELD_SCHOOL_STUDENTS...
alter table ELD_SCHOOL_STUDENTS enable all triggers;
prompt Enabling triggers for ELD_GRADEBOOK_ATTENDANCES...
alter table ELD_GRADEBOOK_ATTENDANCES enable all triggers;
prompt Enabling triggers for ELD_GRADEBOOK_SCORES...
alter table ELD_GRADEBOOK_SCORES enable all triggers;
prompt Enabling triggers for ELD_GROUP_MEMBERS...
alter table ELD_GROUP_MEMBERS enable all triggers;
prompt Enabling triggers for ELD_IMAGES...
alter table ELD_IMAGES enable all triggers;
prompt Enabling triggers for ELD_MESSAGES...
alter table ELD_MESSAGES enable all triggers;
prompt Enabling triggers for ELD_NEWS...
alter table ELD_NEWS enable all triggers;
prompt Enabling triggers for ELD_NEW_COMMENTS...
alter table ELD_NEW_COMMENTS enable all triggers;
prompt Enabling triggers for ELD_PARENTS...
alter table ELD_PARENTS enable all triggers;
prompt Enabling triggers for ELD_PARENTS_TYPES...
alter table ELD_PARENTS_TYPES enable all triggers;
prompt Enabling triggers for ELD_QUARTER_SCORES...
alter table ELD_QUARTER_SCORES enable all triggers;
prompt Enabling triggers for ELD_SCHEDULE...
alter table ELD_SCHEDULE enable all triggers;
prompt Enabling triggers for ELD_SCHOOL_STUDENTS_AND_PARENTS...
alter table ELD_SCHOOL_STUDENTS_AND_PARENTS enable all triggers;
prompt Enabling triggers for ELD_SHEDULE_LESSONS...
alter table ELD_SHEDULE_LESSONS enable all triggers;
prompt Enabling triggers for ELD_USER_COMMENTS...
alter table ELD_USER_COMMENTS enable all triggers;
prompt Enabling triggers for ELD_USERS_TYPES...
alter table ELD_USERS_TYPES enable all triggers;

set feedback on
set define on
prompt Done
